### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by arjung128** [umbertogriffo/fast-near-duplicate-image-search#2]
Hi! Thank you very much for making this open-source!

I tried installing the package using multiple ways (Option 1 in INSTALL.md: ./install.sh, option 3 in INSTALL.md, and make all) but I still get: `-bash: deduplication: command not found`.

Option 1 was mostly successful with the exception of the installation of mkl-ftt. `make all` failed with the following error:

```
which: no activate in (/home/arjung2/.conda/envs/fast_near_duplicate_img_src_py3/bin:/opt/apps/swsuite/bin:/usr/local/cuda-10.1/bin:/opt/apps/openmpi-4.0.0-gcc-4.8.5/bin:/usr/local/cuda/bin:/usr/lib64/qt-3.3/bin:/opt/apps/anaconda3/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/home/arjung2/.local/bin:/home/arjung2/bin)
echo 

source  && conda env create -f environment.yml && conda deactivate
/bin/bash: line 0: source: filename argument required
source: usage: source filename [arguments]
make: *** [setup] Error 2
```

Any ideas? Thank you once again for making this work open-source!

**Comment by umbertogriffo** [comment]
Hi, @arjung128 in which operating system are you installing the library? Linux MacOS?

**Comment by voidcase** [comment]
Hi, I am also having this problem using pip installation. I am on Ubuntu 19.10.
[here is an issue about it on mkl-fft from 2018](https://github.com/IntelPython/mkl_fft/issues/26)

**Comment by umbertogriffo** [comment]
@arjung128 and @voidcase The procedures now should work. I removed the dependency with `mkl-ftt`, and I moved from Anaconda to Virtualenv. The [INSTALL.md](https://github.com/umbertogriffo/fast-near-duplicate-image-search/blob/master/docs/INSTALL.md) has been updated.

**Comment by umbertogriffo** [comment]
@voidcase let me know if it works so I can close the issue. Thanks!

**Comment by voidcase** [comment]
@umbertogriffo installation seems to work fine now, thanks :)
